SET SERVEROUTPUT ON;

DECLARE

  MINHAEXE EXCEPTION;
  n NUMBER := &n;

BEGIN

  FOR i IN &i .. n LOOP
    dbms_output.put_line(i * i);
    IF i * 2 = 10 THEN
      RAISE MINHAEXE;
    END IF;
  END LOOP;

EXCEPTION
  WHEN MINHAEXE THEN
    RAISE_APPLICATION_ERROR(-20015, 'Você caiu na exceção');
END;

SELECT SUM(1+5) FROM DUAL;
SELECT AVG(CODIGO_CARGO) FROM CARGO;
SELECT COUNT(1) FROM CARGO;
SELECT MIN(CODIGO_CARGO) FROM CARGO;
SELECT MAX(CODIGO_CARGO) FROM CARGO;

SELECT * FROM CARGO;